"""Make employee_id unique

Revision ID: c7aa9fe99147
Revises: c257ea0c0863
Create Date: 2026-02-19 21:38:52.068948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c7aa9fe99147'
down_revision: Union[str, Sequence[str], None] = 'c257ea0c0863'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employee', 'employee_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employee', 'employee_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
