"""Remove Company table

Revision ID: e1b9526cb3c3
Revises: c7aa9fe99147
Create Date: 2026-02-19 21:55:15.245590

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e1b9526cb3c3'
down_revision: Union[str, Sequence[str], None] = 'c7aa9fe99147'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employee', 'employee_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employee', 'employee_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
