"""add created_at to finance

Revision ID: 0222896a20c0
Revises: 6ff3f4172001
Create Date: 2026-04-06 12:19:39.415788

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0222896a20c0'
down_revision: Union[str, Sequence[str], None] = '6ff3f4172001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('finance_edit_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('finance_id', sa.Integer(), nullable=False),
    sa.Column('field_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('old_value', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('new_value', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('edited_by', sa.Integer(), nullable=True),
    sa.Column('edited_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['edited_by'], ['admin.id'], ),
    sa.ForeignKeyConstraint(['finance_id'], ['finance.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_finance_edit_history_id'), 'finance_edit_history', ['id'], unique=False)
    op.add_column('finance', sa.Column('created_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('finance', 'created_at')
    op.drop_index(op.f('ix_finance_edit_history_id'), table_name='finance_edit_history')
    op.drop_table('finance_edit_history')
    # ### end Alembic commands ###
