"""initial_schema

Revision ID: 6ff3f4172001
Revises: 
Create Date: 2026-04-04 13:09:47.029116

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '6ff3f4172001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('company_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('website', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('access_key', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_id'), 'admin', ['id'], unique=False)
    op.create_table('attendance_raw',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('serial_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('employee_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attendance_raw_id'), 'attendance_raw', ['id'], unique=False)
    op.create_table('employee',
    sa.Column('employee_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('bank_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('bank_account_title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('bank_branch_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('bank_account_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('bank_iban_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('initial_base_salary', sa.Float(), nullable=False),
    sa.Column('current_base_salary', sa.Float(), nullable=False),
    sa.Column('date_of_joining', sa.Date(), nullable=False),
    sa.Column('fulltime_joining_date', sa.Date(), nullable=True),
    sa.Column('last_increment_date', sa.Date(), nullable=True),
    sa.Column('increment_amount', sa.Float(), nullable=False),
    sa.Column('department', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('home_address', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('designation', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cnic', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('actual_date_of_birth', sa.Date(), nullable=True),
    sa.Column('hobbies', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('vehicle_registration_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('badge_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('profile_pic_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employee_id'), 'employee', ['id'], unique=False)
    op.create_table('financecategory',
    sa.Column('category_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('color_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('category_id')
    )
    op.create_index(op.f('ix_financecategory_category_id'), 'financecategory', ['category_id'], unique=False)
    op.create_table('item_category',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_item_category_id'), 'item_category', ['id'], unique=False)
    op.create_table('jwt_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_ip', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('token', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jwt_tokens_id'), 'jwt_tokens', ['id'], unique=False)
    op.create_table('employee_increment_history',
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('increment_amount', sa.Float(), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('finance',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('tax_deductions', sa.Float(), nullable=False),
    sa.Column('cheque_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('added_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['added_by'], ['admin.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['financecategory.category_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_finance_id'), 'finance', ['id'], unique=False)
    op.create_table('store_items',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['item_category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_store_items_id'), 'store_items', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_store_items_id'), table_name='store_items')
    op.drop_table('store_items')
    op.drop_index(op.f('ix_finance_id'), table_name='finance')
    op.drop_table('finance')
    op.drop_table('employee_increment_history')
    op.drop_index(op.f('ix_jwt_tokens_id'), table_name='jwt_tokens')
    op.drop_table('jwt_tokens')
    op.drop_index(op.f('ix_item_category_id'), table_name='item_category')
    op.drop_table('item_category')
    op.drop_index(op.f('ix_financecategory_category_id'), table_name='financecategory')
    op.drop_table('financecategory')
    op.drop_index(op.f('ix_employee_id'), table_name='employee')
    op.drop_table('employee')
    op.drop_index(op.f('ix_attendance_raw_id'), table_name='attendance_raw')
    op.drop_table('attendance_raw')
    op.drop_index(op.f('ix_admin_id'), table_name='admin')
    op.drop_table('admin')
    # ### end Alembic commands ###
